### ISSUE TITLE
Power Commands as Scripts

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-metal#31]
The IPMI commands are, much like the dhcpd.flight file (#30), specific to the internal test use-case. In reality, there are many different BMC tools and only some support different types of hardware.

The proposed idea is that each node would have a separate script for each power command:
- `power_on`
- `power_off`
- `power_status`

The metal command line would then just execute this script.

It's probably worth having a defined API for the scripts of some sort:
- Executed with bash
- Exit 0 on success (all other codes = failure)
- All output returned to terminal
- Some argument consistency? (passing through metadata as env variables `NODE=node01 BMCUSER=admin BMCPASS=mypassword`)

It's also worth including edit helpers for these too - #29.

**Comment by ColonelPanics** [comment]
Example power scripts which use variables from the node key/val definitions can be found at https://github.com/openflighthpc/flight-metal/tree/dev/template-files/examples/node

**Comment by ColonelPanics** [comment]
Perhaps the scripts could work similar to parameters in [flight-cloud](https://github.com/openflighthpc/flight-cloud/issues) whereby `%mykey%` gets replaced. Although, unlike current versions of flight-cloud, the node metadata could automatically be passed through.

This would allow for parameters to be automatically inherited from the configured node whilst permitting one-off overrides/replacements of values if needs be.

**Comment by WilliamMcCumstie** [comment]
This issue has been mostly implemented in version `0.2.0`. The scripts are now considered content, and the power commands directly run the rendered version.

As `metal` now uses, `edit` and `render`, parameters are not directly passed into the scripts. It also isn't possible to ensure a consistent API output from these scripts, as this would reduce flexibility.

Template rendering similar to `cloud` has been implemented. If we are happy with the new parameter passing, this issue can be closed

**Comment by WilliamMcCumstie** [comment]
As of the `0.3.0` generation of releases, templating and running scripts for power commands are now fully supported
