### ISSUE TITLE
Loosen Node Metadata Constraints

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-metal#32]
Some of the "required" metadata for a node is more specific to test use case (`gateway_ip`, `fqdn`).

Other parts are likely to be more common but are also not required as future changes to functionality would mean this can be bypassed (`bmc_user`, `bmc_password` and `bmc_ip` with the introduction of #31).

This issue proposes the following:
- Remove the requirement for all the above-mentioned keys
- Allow for arbitrary metadata key-val pairs (that could then become used as part of #30)

**Comment by WilliamMcCumstie** [comment]
This was implemented in version `0.2.0`
