### ISSUE TITLE
Metal edit help text

### ISSUE THREAD

**Issue by sierra-tango-echo** [openflighthpc/flight-metal#35]
Can we get the help text for metal edit --fields command updated with an example or similar - currently its just:

```   
  --fields JSON
        The updated fields to be saved
```

That's left me no more enlightened as to how to use it.

**Comment by ColonelPanics** [comment]
Agreed, this is certainly worth having.

In the meantime, I can provide a working example here:
```
flight metal edit node01 --fields "{ \"mac\": \"00:11:22:33:44:55\", \"bmc_ip\": \"10.11.123.11\" }"
```

Where the fields are any of the keys that can be seen in `flight metal edit node01`

**Comment by sierra-tango-echo** [comment]
🤮 Jason

**Comment by WilliamMcCumstie** [comment]
The `--fields` has been removed because JSON is ugly. Parameters are updated with the `update` command. The future of parameters setting on edit TBD

**Comment by WilliamMcCumstie** [comment]
As of version `0.3.3` of metal the parameters are now updated with `metal <level> parameters update`. The `--fields` flag has been removed and the commands no longer use `JSON`
