### ISSUE TITLE
Don't prompt for editor

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-metal#36]
Prompting for an editor provides an unnecessary extra step when running `create`/`edit`. Instead:

- Use the `EDITOR` environment variable
- Default to using vim if `EDITOR` not set

**Comment by WilliamMcCumstie** [comment]
`TTY::Editor` does default to the `EDITOR` env var, so this has already been implemented.

I don't think defaulting to `vim` is a sensible choice as it permanently disables the prompt and `vim` may not be installed. In most cases, the user has either `VISUAL` or `EDITOR` and the prompt isn't an issue. Alternatively, the command might be sandboxed and a manual editor is set anyway

**Comment by WilliamMcCumstie** [comment]
As this issue has been on hold for awhile, it will be closed.
