### ISSUE TITLE
Build Command

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-metal#4]
Use metalware as reference. Command for building nodes.

**Comment by ColonelPanics** [comment]
A general outline of how the build process should go (from meeting with @WilliamMcCumstie @mjtko):

1. Build puts pxe boot files in place for all node
2. Node boots and starts doing kickstart installation
3. Node finishes build and sends a telnet/curl/some form of message to the build server
4. Build notifies of build complete
5. Remove `pxelinux.cfg/01-AA-BB-CC-DD-EE-FF`
6. Build sets node build state to built (to prevent future rebuilding without explicit destroy/delete method)

**Comment by WilliamMcCumstie** [comment]
Done
